FactoryBot.define do
  factory :list do
    # Dynamic - sequence can be searched within api references
    # Unique values in a specific format (for example, e-mail addresses) can be generated using sequences. Sequences are defined by calling sequence in a definition block, and values in a sequence are generated by calling generate:
    sequence(:name) { |n| "my name #{n}" }
    date {nil}
    number {nil}
    sequence(:description) { |n| "the description #{n}" }
  end
end
